### PR TITLE
using config for set up indexes, and making index names global variables in individual indexers

### PR DESCRIPTION
**Pull request by slebras**

### CODE REVIEW

**Comment by jayrbolton** [comment]
hay algunas problemas en pruebas

**Comment by jayrbolton** [comment]
The code looks good to me. I'll check why tests are failing

**Comment by jayrbolton** [comment]
I fixed the config release. Can you fix the set_up_indexes.py code to use the config['global']['aliases'] dict?

**Comment by slebras** [comment]
gotcha, I'll take a looksie

**Comment by jayrbolton** [comment]
Tudo bom

**Pull request merged**
